### ISSUE TITLE
Exceptions: The SSL connection could not be established

### ISSUE THREAD

**Issue by it-AhmedTaha** [mindee/mindee-api-dotnet#160]
I get this exception when I upload a passport using CustomEndpoint on production, it works fine on local. 

Exception:
Mindee.Exceptions.MindeeException: Mindee API client : Unhandled error - The SSL connection could not be established, see inner exception.
at Mindee.Parsing.MindeeApi.PredictAsync[TModel](CustomEndpoint endpoint, PredictParameter predictParameter)
at Mindee.MindeeClient.ParseAsync(CustomEndpoint endpoint)

 ```
var mindeeClient = MindeeClientInit.Create(_configuration["MindeeApiSettings:ApiKey"]);
        var fileInfo = new FileInfo(request.file.FileName);
        var folderPath = Path.Combine(_hostEnvironment.ContentRootPath, "Crm", "Passports");
        Directory.CreateDirectory(folderPath);

        var filePath = Path.Combine(folderPath, fileInfo.Name); 
        await using (var stream = new FileStream(filePath, FileMode.Create))
        {
            await request.file.CopyToAsync(stream, cancellationToken); 
        }
        using (var memoryStream = new MemoryStream(await File.ReadAllBytesAsync(filePath, cancellationToken)))
        {
            return await mindeeClient
                .LoadDocument(memoryStream, fileInfo.Name)
                .ParseAsync(new CustomEndpoint(_configuration["MindeeApiSettings:endpointName"], _configuration["MindeeApiSettings:accountName"], _configuration["MindeeApiSettings:version"]));
        }
```

**Comment by ianardee** [comment]
If it's working locally it's most likely a problem with the server configuration.

Are you able to access the Mindee API from command line on the server, as in:
```
curl -X POST \\
  https://api.mindee.net/v1/products/ACCOUNT_NAME/ENDPOINT_NAME/v1/predict \\
  -H 'Authorization: Token my-api-key-here' \\
  -H 'content-type: multipart/form-data' \\
  -F document=@/path/to/your/file.png
```

**Comment by it-AhmedTaha** [comment]
Yes you are correct. Thank you.
